---
version: '3.9'

networks:
  macvlan_network:
    external: true
    name: "${DOCKER_NETWORK}"

services:
  nginx-setup:
    build: ./build/
    pull_policy: build
    image: tautulli-setup
    container_name: tautulli-setup
    volumes:
      - "${SSL}:/ssl"
      - "${NGINX}:/nginx"

  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: tautulli-nginx
    restart: always
    volumes:
      - "${NGINX}/nginx.conf:/etc/nginx/nginx.conf"
      - "${SSL}:/ssl"
    networks:
      macvlan_network:
        ipv4_address: "${IP_ADDRESS}"
    depends_on:
      nginx-setup:
        condition: service_completed_successfully

  tautulli:
    image: tautulli/tautulli
    pull_policy: always
    container_name: tautulli
    restart: always
    volumes:
      - "${TAUTULLI_CONFIG}:/config"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    network_mode: "service:nginx"
    depends_on:
      nginx:
        condition: service_started
