services:
  tautulli:
    image: tautulli/tautulli
    pull_policy: always
    container_name: tautulli
    restart: always
    volumes:
      - "${TAUTULLI_CONFIG}:/config"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    ports:
      - "8181:8181"
